#! /usr/bin/env python3
#


__all__ = [
    "HEADER_2_SYMBOLS",
]


HEADER_2_SYMBOLS = {
    "stdlib.h": [
        # https://en.cppreference.com/w/c/header/stdlib.html
        "size_t",
        "div_t",
        "ldiv_t",
        "lldiv_t",
        #
        "NULL",
        "EXIT_FAILURE",
        "EXIT_SUCCESS",
        "RAND_MAX",
        "MB_CUR_MAX",
        #
        # "call_once",
        "atof",
        "atoi",
        "atol",
        "atoll",
        "strfromd",
        "strfromf",
        "strfroml",
        "strtod",
        "strtof",
        "strtold",
        "strtol",
        "strtoll",
        "strtoul",
        "strtoull",
        "rand",
        "srand",
        "aligned_alloc",
        "calloc",
        "free",
        "free_sized",
        "free_aligned_sized",
        "malloc",
        "realloc",
        "abort",
        "atexit",
        "at_quick_exit",
        "exit",
        "_Exit",
        "getenv",
        "quick_exit",
        "system",
        "bsearch",
        "qsort",
        "abs",
        "labs",
        "llabs",
        "div",
        "ldiv",
        "lldiv",
        "mblen",
        "mbtowc",
        "wctomb",
        "mbstowcs",
        "wcstombs",
        "memalignment",
        #
        "strfromd32",
        "strfromd64",
        "strfromd128",
        "strtod32",
        "strtod64",
        "strtod128",
        #
        "set_constraint_handler_s",
        "abort_handler_s",
        "ignore_handler_s",
        "getenv_s",
        "bsearch_s",
        "qsort_s",
        "wctomb_s",
        "mbstowcs_s",
        "wcstombs_s",
    ]
    + [
        "posix_memalign",
        "reallocf",
        "valloc",
        #
        "clearenv",
        "getenv",
        "setenv",
        "putenv",
        "unsetenv",
        #
        "rand_r",
    ],
    "cstdlib": [
        # https://en.cppreference.com/w/cpp/header/cstdlib.html
        "std::size_t",
        "std::div_t",
        "std::ldiv_t",
        "std::lldiv_t",
        #
        "std::abort",
        "std::atexit",
        "std::at_quick_exit",
        "std::exit",
        "std::_Exit",
        "std::quick_exit",
        "std::getenv",
        "std::system",
        "std::aligned_alloc",
        "std::calloc",
        "std::free",
        "std::malloc",
        "std::realloc",
        "std::atof",
        "std::atoi",
        "std::atol",
        "std::atoll",
        "std::strtod",
        "std::strtof",
        "std::strtold",
        "std::strtol",
        "std::strtoll",
        "std::strtoul",
        "std::strtoull",
        "std::mblen",
        "std::mbtowc",
        "std::wctomb",
        "std::mbstowcs",
        "std::wcstombs",
        "std::bsearch",
        "std::bsearch",
        "std::qsort",
        "std::qsort",
        "std::rand",
        "std::srand",
        "std::abs",
        "std::labs",
        "std::llabs",
        "std::div",
        "std::ldiv",
        "std::lldiv",
    ],
}


HEADER_2_SYMBOLS["cstdlib"] = HEADER_2_SYMBOLS["stdlib.h"] + HEADER_2_SYMBOLS["cstdlib"]
