#! /usr/bin/env python3
#


__all__ = [
    "HEADER_2_SYMBOLS",
]


HEADER_2_SYMBOLS = {
    "sys/socket.h": [
        # https://pubs.opengroup.org/onlinepubs/7908799/xns/syssocket.h.html
        "socklen_t",
        "sa_family_t",
        "sockaddr",
        "msghdr",
        "cmsghdr",
        "SCM_RIGHTS",
        "CMSG_DATA",
        "CMSG_NXTHDR",
        "CMSG_FIRSTHDR",
        "linger",
        "SOCK_DGRAM",
        "SOCK_STREAM",
        "SOCK_SEQPACKET",
        "SOL_SOCKET",
        "SO_ACCEPTCONN",
        "SO_BROADCAST",
        "SO_DEBUG",
        "SO_DONTROUTE",
        "SO_ERROR",
        "SO_KEEPALIVE",
        "SO_LINGER",
        "SO_OOBINLINE",
        "SO_RCVBUF",
        "SO_RCVLOWAT",
        "SO_RCVTIMEO",
        "SO_REUSEADDR",
        "SO_SNDBUF",
        "SO_SNDLOWAT",
        "SO_SNDTIMEO",
        "SO_TYPE",
        "MSG_CTRUNC",
        "MSG_DONTROUTE",
        "MSG_EOR",
        "MSG_OOB",
        "MSG_PEEK",
        "MSG_TRUNC",
        "MSG_WAITALL",
        "AF_UNIX",
        "AF_UNSPEC",
        "AF_INET",
        "SHUT_RD",
        "SHUT_WR",
        "SHUT_RDWR",
        "accept",
        "bind",
        "connect",
        "getpeername",
        "getsockname",
        "getsockopt",
        "listen",
        "recv",
        "recvfrom",
        "recvmsg",
        "send",
        "sendmsg",
        "sendto",
        "setsockopt",
        "shutdown",
        "socket",
        "socketpair",
    ],
}
