#! /usr/bin/env python3
#


__all__ = [
    "HEADER_2_SYMBOLS",
]


HEADER_2_SYMBOLS = {
    "sys/stat.h": [
        # https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/sys_stat.h.html
        "stat",
        "blkcnt_t",
        "blksize_t",
        "dev_t",
        "ino_t",
        "mode_t",
        "nlink_t",
        "uid_t",
        "gid_t",
        "off_t",
        "time_t",
        "timespec",
        "S_IFMT",
        "S_IFBLK",
        "S_IFCHR",
        "S_IFIFO",
        "S_IFREG",
        "S_IFDIR",
        "S_IFLNK",
        "S_IFSOCK",
        "S_IRWXU",
        "S_IRUSR",
        "S_IWUSR",
        "S_IXUSR",
        "S_IRWXG",
        "S_IRGRP",
        "S_IWGRP",
        "S_IXGRP",
        "S_IRWXO",
        "S_IROTH",
        "S_IWOTH",
        "S_IXOTH",
        "S_ISUID",
        "S_ISGID",
        "S_ISVTX",
        "S_ISBLK",
        "S_ISCHR",
        "S_ISDIR",
        "S_ISFIFO",
        "S_ISREG",
        "S_ISLNK",
        "S_ISSOCK",
        "S_TYPEISMQ",
        "S_TYPEISSEM",
        "S_TYPEISSHM",
        "S_TYPEISTMO",
        "chmod",
        "fchmod",
        "fchmodat",
        "fstat",
        "fstatat",
        "futimens",
        "lstat",
        "mkdir",
        "mkdirat",
        "mkfifo",
        "mkfifoat",
        "mknod",
        "mknodat",
        "stat",
        "umask",
        "utimensat",
    ],
}
