#! /usr/bin/env python3
#


__all__ = [
    "HEADER_2_SYMBOLS",
    "HEADER_2_PREFIXES",
]


HEADER_2_SYMBOLS = {
    "iterator": [
        "std::advance",
        "std::back_insert_iterator",
        "std::back_inserter",
        "std::begin",
        "std::bidirectional_iterator",
        "std::bidirectional_iterator_tag",
        "std::cbegin",
        "std::cend",
        "std::common_iterator",
        "std::contiguous_iterator",
        "std::contiguous_iterator_tag",
        "std::counted_iterator",
        "std::crbegin",
        "std::crend",
        "std::data",
        "std::default_sentinel",
        "std::default_sentinel_t",
        "std::disable_sized_sentinel_for",
        "std::distance",
        "std::empty",
        "std::end",
        "std::forward_iterator",
        "std::forward_iterator_tag",
        "std::front_insert_iterator",
        "std::front_inserter",
        "std::incrementable",
        "std::incrementable_traits",
        "std::indirect_binary_predicate",
        "std::indirect_equivalence_relation",
        "std::indirect_result_t",
        "std::indirect_strict_weak_order",
        "std::indirect_unary_predicate",
        "std::indirectly_comparable",
        "std::indirectly_copyable",
        "std::indirectly_copyable_storable",
        "std::indirectly_movable",
        "std::indirectly_movable_storable",
        "std::indirectly_readable_traits",
        "std::indirectly_regular_unary_invocable",
        "std::indirectly_swappable",
        "std::indirectly_unary_invocable",
        "std::indirectly_writable",
        "std::input_iterator",
        "std::input_iterator_tag",
        "std::input_or_output_iterator",
        "std::insert_iterator",
        "std::inserter",
        "std::istream_iterator",
        "std::istreambuf_iterator",
        "std::iter_common_reference_t",
        "std::iter_difference_t",
        "std::iter_reference_t",
        "std::iter_rvalue_reference_t",
        "std::iter_value_t",
        "std::iterator",
        "std::iterator_traits",
        "std::make_move_iterator",
        "std::make_reverse_iterator",
        "std::mergeable",
        "std::move_iterator",
        "std::move_sentinel",
        "std::next",
        "std::ostream_iterator",
        "std::ostreambuf_iterator",
        "std::output_iterator",
        "std::output_iterator_tag",
        "std::permutable",
        "std::prev",
        "std::projected",
        "std::random_access_iterator",
        "std::random_access_iterator_tag",
        "std::range::advance",
        "std::range::distance",
        "std::range::next",
        "std::range::prev",
        "std::ranges::iter_move",
        "std::ranges::iter_swap",
        "std::rbegin",
        "std::rend",
        "std::reverse_iterator",
        "std::sentinel_for",
        "std::size",
        "std::sized_sentinel_for",
        "std::sortable",
        "std::ssize",
        "std::unreachable_sentinel",
        "std::unreachable_sentinel_t",
        "std::weakly_incrementable",
    ],
}


HEADER_2_PREFIXES = {
    "iterator": [
        "std::bidirectional_iterator_tag",
        "std::contiguous_iterator_tag",
        "std::default_sentinel_t",
        "std::forward_iterator_tag",
        "std::input_iterator_tag",
        "std::output_iterator_tag",
        "std::random_access_iterator_tag",
        "std::unreachable_sentinel_t",
    ],
}
